version: '3.8'
services:
  postgres:
    build: ./infra/db
    restart: always
    environment:
      POSTGRES_USER: humaid
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rouh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: