version: "3.9"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: rouh-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rouh
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rouh-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: rouh-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  postgres:
  redis:
  minio:

